    /usr/local/TensorRT-8.4.1.4/bin/trtexec \
	--onnx=/root/onnx/segformer.b2.1024x1024.city.160k_v2.onnx \
    --minShapes=input:1x3x1024x1024 \
    --optShapes=input:4x3x1024x1024 \
    --maxShapes=input:8x3x1024x1024 \
    --workspace=23000 \
    --saveEngine=/home/pengsky/TRT-Hackathon-2022-SegFormer/TRT/engine/segFormer_ln_best_v2.plan \
    --verbose \
    --best \
    --precisionConstraints=obey \
    --calib="/home/pengsky/TRT-Hackathon-2022-SegFormer/TRT/python/segformer_calibration_backup.cache" \
    --tacticSources=-CUDNN,+CUBLAS \
    --plugins=/home/pengsky/TRT-Hackathon-2022-SegFormer/TRT/LayerNormPlugin-V3.0-OneFlow-TRT8/LayerNorm.so \
    > /home/pengsky/TRT-Hackathon-2022-SegFormer/TRT/log/segformer_ln_best_v2.txt
